language: php

php:
    - 7.1
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 7.2
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

branches:
    only:
        - master
        - 1.x
        - 2.x
        - 3.x

before_script:
    - composer update --prefer-source $COMPOSER_FLAGS

script:
    - make test
